-- Purpose: Provides a detailed breakdown of table size and fragmentation, critical for storage prioritization.
--
SELECT
    t.OWNER,
    t.TABLE_NAME,
    t.BLOCKS * ts.BLOCK_SIZE AS TABLE_SIZE_BYTES,
    SUM(seg.BYTES) AS SEGMENT_SIZE_BYTES,
    (SUM(seg.BYTES) - t.BLOCKS * ts.BLOCK_SIZE) AS FRAGMENTATION_BYTES,
    COUNT(p.PARTITION_NAME) AS PARTITION_COUNT
FROM
    DBA_TABLES t
LEFT JOIN
    DBA_TAB_PARTITIONS p ON t.TABLE_NAME = p.TABLE_NAME AND t.OWNER = p.TABLE_OWNER
LEFT JOIN
    DBA_SEGMENTS seg ON seg.SEGMENT_NAME = t.TABLE_NAME AND seg.OWNER = t.OWNER
LEFT JOIN
    DBA_TABLESPACES ts ON ts.TABLESPACE_NAME = t.TABLESPACE_NAME
WHERE
    t.OWNER NOT IN ('SYS', 'SYSTEM')
GROUP BY
    t.OWNER, t.TABLE_NAME, t.BLOCKS, ts.BLOCK_SIZE
ORDER BY
    TABLE_SIZE_BYTES DESC, FRAGMENTATION_BYTES DESC;
